apiVersion: v1
kind: Service
metadata:
  name:  myapp-service
spec:
  selector:
    app:  myapp
    type: front-end
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  80
    port:  80
    targetPort:  30008